"""Curated software catalog - 20 programs researched against their real
GitHub/Docker Hub listings on 2026-08-07 (see the design-treatment
artifact), not an open image installer. Every entry here is deliberately
narrow: a fixed image+tag, a fixed port map, a fixed named-volume set.
There is no "paste any image" path anywhere in this service - that's the
whole point of "curated" (see the treatment doc's Install scope decision).

Design note on HOW this installs, which differs from the original
pitch's "writes docker-compose.yml" framing: this container has no bind
mount of the repo's docker-compose.yml and no `docker compose` CLI in its
own image (checked before writing this - see Dockerfile). It only has
docker.sock. So install/remove goes straight through the Docker SDK
(docker_client.containers.run/.stop/.remove) instead of editing the
compose file at all. A catalog container is a real, independently-
running Docker container on the same `stacknet` network, with its own
`restart: unless-stopped` policy - it survives a reboot or crash the same
way a compose service would, but a `docker compose down && up` on the
main stack won't touch it (compose has never heard of it). That's a
strictly smaller blast radius than the alternative (a bad compose-file
write breaking `docker compose up` for the entire stack), which is why
this shape won out over the treatment doc's original assumption.
"""

CATALOG_LABEL = "media-stack.catalog"  # label key marking a container as catalog-managed
NETWORK = "stacknet"

CATALOG: list[dict] = [
    # ---- Monitoring & observability ----
    {
        "id": "uptime-kuma",
        "name": "Uptime Kuma",
        "category": "Monitoring & observability",
        "pitch": "Pings every service's HTTP endpoint (and can watch Docker containers directly) - pages you the moment one goes dark, before you notice from the couch.",
        "image": "louislam/uptime-kuma",
        "tag": "2",
        "ports": {"3001/tcp": 3001},
        "volumes": {"catalog_uptime_kuma_data": {"bind": "/app/data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~90MB RAM",
        "doc_url": "https://github.com/louislam/uptime-kuma",
        "caveat": None,
    },
    {
        "id": "beszel",
        "name": "Beszel",
        "category": "Monitoring & observability",
        "pitch": "Host + per-container CPU/RAM/disk/network, hub-and-agent. ~50x lighter than Grafana+Prometheus for this stack's scale.",
        "image": "henrygd/beszel",
        "tag": "latest",
        "ports": {"8090/tcp": 8090},
        "volumes": {"catalog_beszel_data": {"bind": "/beszel_data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "<10MB RAM (hub); agent installs separately per host",
        "doc_url": "https://github.com/henrygd/beszel",
        "caveat": "Hub only - the agent that actually reports container stats runs as a second, separate container (not installed by this one-click; see docs).",
    },
    {
        "id": "scrutiny",
        "name": "Scrutiny",
        "category": "Monitoring & observability",
        "pitch": "S.M.A.R.T. drive health merged with Backblaze real-world failure-rate data - flags a dying disk weeks before it takes the library down.",
        "image": "ghcr.io/analogj/scrutiny",
        "tag": "latest-omnibus",
        "ports": {"8080/tcp": 8085},
        "volumes": {"catalog_scrutiny_data": {"bind": "/opt/scrutiny/config", "mode": "rw"}},
        "environment": {},
        "cap_add": ["SYS_RAWIO"],
        "devices": [],
        "footprint": "~70MB RAM",
        "doc_url": "https://github.com/analogj/scrutiny",
        "caveat": "Needs SYS_RAWIO plus direct device passthrough to read SMART data - installed with cap_add granted, but device passthrough (which physical disks) needs a one-time manual edit before it can see any drives.",
    },
    {
        "id": "dozzle",
        "name": "Dozzle",
        "category": "Monitoring & observability",
        "pitch": "Real-time log viewer across every container, 7MB image, nothing stored - the \"just let me see what radarr just logged\" tool without opening a shell.",
        "image": "amir20/dozzle",
        "tag": "latest",
        "ports": {"8080/tcp": 8081},
        "volumes": {},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~15MB RAM",
        "doc_url": "https://github.com/amir20/dozzle",
        "caveat": None,
        "docker_sock": True,
    },
    {
        "id": "speedtest-tracker",
        "name": "Speedtest Tracker",
        "category": "Monitoring & observability",
        "pitch": "Runs a speed test on a schedule, graphs it over time - turns \"is the ISP throttling us\" from a feeling into a chart you can point at.",
        "image": "henrywhitaker3/speedtest-tracker",
        "tag": "latest",
        "ports": {"80/tcp": 8765},
        "volumes": {"catalog_speedtest_data": {"bind": "/config", "mode": "rw"}},
        "environment": {"OOKLA_EULA_GDPR": "true"},
        "cap_add": [],
        "devices": [],
        "footprint": "~120MB RAM",
        "doc_url": "https://github.com/henrywhitaker3/Speedtest-Tracker",
        "caveat": "No official ARM image from the maintainer - fine on this host.",
    },
    # ---- Notifications ----
    {
        "id": "notifiarr",
        "name": "Notifiarr",
        "category": "Notifications",
        "pitch": "One client that every *arr app in this fleet reports to, fanning out to Discord/webhooks - replaces per-app notification config with one place to manage it.",
        "image": "golift/notifiarr",
        "tag": "latest",
        "ports": {},
        "volumes": {"catalog_notifiarr_data": {"bind": "/config", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~55MB RAM",
        "doc_url": "https://github.com/Notifiarr/notifiarr",
        "caveat": "Needs each *arr app's URL + API key entered in its own config UI after install - not wired automatically by this installer.",
    },
    {
        "id": "ntfy",
        "name": "ntfy",
        "category": "Notifications",
        "pitch": "Push straight to your phone/desktop with a plain HTTP POST, no account or app-store dependency.",
        "image": "binwiederhier/ntfy",
        "tag": "latest",
        "ports": {"80/tcp": 8093},
        "volumes": {"catalog_ntfy_data": {"bind": "/var/lib/ntfy", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~30MB RAM",
        "doc_url": "https://github.com/binwiederhier/ntfy",
        "caveat": None,
        "command": ["serve"],
    },
    # ---- Indexer & library completion ----
    {
        "id": "flaresolverr",
        "name": "FlareSolverr",
        "category": "Indexer & library completion",
        "pitch": "Solves Cloudflare challenges Prowlarr can't get through directly - wires in as a Prowlarr indexer proxy.",
        "image": "ghcr.io/flaresolverr/flaresolverr",
        "tag": "latest",
        "ports": {"8191/tcp": 8191},
        "volumes": {},
        "environment": {"LOG_LEVEL": "info"},
        "cap_add": [],
        "devices": [],
        "footprint": "~180MB RAM (headless browser)",
        "doc_url": "https://github.com/FlareSolverr/FlareSolverr",
        "caveat": "After install, add it as a proxy in Prowlarr's Settings -> Indexers manually - not auto-wired.",
    },
    {
        "id": "gaps2",
        "name": "GAPS-2",
        "category": "Indexer & library completion",
        "pitch": "Scans Plex for collections you partially own and finds the missing entries, sends them straight to Radarr by TMDB id.",
        "image": "primetime43/gaps-2",
        "tag": "latest",
        "ports": {"4277/tcp": 4277},
        "volumes": {"catalog_gaps2_data": {"bind": "/data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~150MB RAM",
        "doc_url": "https://github.com/primetime43/GAPS-2",
        "caveat": "Fork of the unmaintained original housewrecker/gaps - this is the actively maintained one.",
    },
    {
        "id": "recyclarr",
        "name": "Recyclarr",
        "category": "Indexer & library completion",
        "pitch": "Continuously syncs TRaSH-Guides quality profiles and custom formats into Radarr/Sonarr - automates what the trash-guides-applier skill does by hand.",
        "image": "ghcr.io/recyclarr/recyclarr",
        "tag": "8",
        "ports": {},
        "volumes": {"catalog_recyclarr_data": {"bind": "/config", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~20MB RAM (scheduled run, no persistent server)",
        "doc_url": "https://github.com/recyclarr/recyclarr",
        "caveat": "Tag pinned to major version 8 on purpose - the :latest tag is no longer published upstream.",
    },
    # ---- Library quality & sync ----
    {
        "id": "tdarr",
        "name": "Tdarr",
        "category": "Library quality & sync",
        "pitch": "Distributed transcode automation - re-encodes the library against rules you set, commonly cutting storage 40-50% with no visible quality loss.",
        "image": "haveagitgat/tdarr",
        "tag": "latest",
        "ports": {"8265/tcp": 8265, "8266/tcp": 8266},
        "volumes": {
            "catalog_tdarr_server": {"bind": "/app/server", "mode": "rw"},
            "catalog_tdarr_configs": {"bind": "/app/configs", "mode": "rw"},
            "catalog_tdarr_logs": {"bind": "/app/logs", "mode": "rw"},
        },
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~200MB RAM; transcode work itself is CPU/GPU-bound",
        "doc_url": "https://github.com/HaveAGitGat/Tdarr",
        "caveat": "Server only - a Tdarr_Node (separate container) does the actual transcoding and isn't installed automatically.",
    },
    {
        "id": "watchstate",
        "name": "Watchstate",
        "category": "Library quality & sync",
        "pitch": "Syncs watch/play state between Plex and Trakt - broader scope than PlexTraktSync, which this replaces outright.",
        "image": "ghcr.io/arabcoders/watchstate",
        "tag": "latest",
        "ports": {"8080/tcp": 8096},
        "volumes": {"catalog_watchstate_data": {"bind": "/config", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~60MB RAM",
        "doc_url": "https://github.com/arabcoders/watchstate",
        "caveat": None,
    },
    {
        "id": "plexanisync",
        "name": "PlexAniSync",
        "category": "Library quality & sync",
        "pitch": "Syncs the anime library's watch status to AniList - a direct fit given how anime-heavy this specific library is (Radarr Anime).",
        "image": "ghcr.io/rickdb/plexanisync",
        "tag": "latest",
        "ports": {},
        "volumes": {"catalog_plexanisync_data": {"bind": "/data", "mode": "rw"}},
        "environment": {"PLEX_URL": "http://plex:32400"},
        "cap_add": [],
        "devices": [],
        "footprint": "~40MB RAM (scheduled run)",
        "doc_url": "https://github.com/RickDB/PlexAniSync",
        "caveat": "Needs PLEX_TOKEN and AniList credentials added to its config after install.",
    },
    # ---- Household & access ----
    {
        "id": "wizarr",
        "name": "Wizarr",
        "category": "Household & access",
        "pitch": "Self-service invite links for Plex - a friend clicks one link and is onboarded, including a walkthrough to install Plex and use Seerr.",
        "image": "ghcr.io/wizarrrr/wizarr",
        "tag": "latest",
        "ports": {"5690/tcp": 5690},
        "volumes": {"catalog_wizarr_data": {"bind": "/data/database", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~70MB RAM",
        "doc_url": "https://github.com/wizarrrr/wizarr",
        "caveat": None,
    },
    {
        "id": "homepage",
        "name": "Homepage",
        "category": "Household & access",
        "pitch": "A simple bookmark/status launcher for household members who shouldn't see the operator console - separate audience from the control panel.",
        "image": "ghcr.io/gethomepage/homepage",
        "tag": "latest",
        "ports": {"3000/tcp": 3009},
        "volumes": {"catalog_homepage_config": {"bind": "/app/config", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~60MB RAM",
        "doc_url": "https://github.com/gethomepage/homepage",
        "caveat": "Chosen over Homarr - Homarr's GitHub repo currently shows archived. Config-as-code, edited via files in its volume, not a UI.",
    },
    # ---- Docker & host management ----
    {
        "id": "portainer",
        "name": "Portainer CE",
        "category": "Docker & host management",
        "pitch": "Deeper stack/volume/network management than the control panel's app-specific container controls.",
        "image": "portainer/portainer-ce",
        "tag": "lts",
        "ports": {"9443/tcp": 9443},
        "volumes": {"catalog_portainer_data": {"bind": "/data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~80MB RAM",
        "doc_url": "https://github.com/portainer/portainer",
        "caveat": "Overlaps with the control panel's own docker.sock access - different job (general admin vs. app-specific actions), not redundant, but both can restart the same container.",
        "docker_sock": True,
    },
    {
        "id": "filebrowser",
        "name": "Filebrowser",
        "category": "Docker & host management",
        "pitch": "A plain web file manager scoped to the media/config directories - upload, rename, preview without a terminal.",
        "image": "filebrowser/filebrowser",
        "tag": "latest",
        "ports": {"80/tcp": 8082},
        "volumes": {"catalog_filebrowser_data": {"bind": "/database", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~25MB RAM",
        "doc_url": "https://github.com/filebrowser/filebrowser",
        "caveat": "Installed with no media/config bind mount by default - add one manually before use, scoped as tightly as you're comfortable with.",
    },
    {
        "id": "caddy",
        "name": "Caddy",
        "category": "Docker & host management",
        "pitch": "Reverse proxy with fully automatic HTTPS - two lines of config gets every service in this catalog a real certificate instead of a bare IP:port.",
        "image": "caddy",
        "tag": "latest",
        "ports": {"80/tcp": 80, "443/tcp": 443},
        "volumes": {
            "catalog_caddy_data": {"bind": "/data", "mode": "rw"},
            "catalog_caddy_config": {"bind": "/config", "mode": "rw"},
        },
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~15MB RAM",
        "doc_url": "https://caddyserver.com/docs/",
        "caveat": "Installed with a blank Caddyfile - add site blocks for each service you want proxied.",
    },
    # ---- Security & unified access ----
    {
        "id": "vaultwarden",
        "name": "Vaultwarden",
        "category": "Security & unified access",
        "pitch": "Self-hosted, Bitwarden-compatible password vault - genuinely useful given how many per-service API keys this stack alone manages.",
        "image": "vaultwarden/server",
        "tag": "latest",
        "ports": {"80/tcp": 8222},
        "volumes": {"catalog_vaultwarden_data": {"bind": "/data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~30MB RAM",
        "doc_url": "https://github.com/dani-garcia/vaultwarden",
        "caveat": "Only use this behind the Caddy entry above - a password manager served over bare HTTP is a real risk, not installed with HTTPS on its own.",
    },
    {
        "id": "organizr",
        "name": "Organizr",
        "category": "Security & unified access",
        "pitch": "Embeds every service's actual web UI as tabs in one shell - keeps you inside the page instead of bouncing per app, unlike Homepage's link-launcher.",
        "image": "ghcr.io/organizr/organizr",
        "tag": "latest",
        "ports": {"80/tcp": 8083},
        "volumes": {"catalog_organizr_data": {"bind": "/config", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~50MB RAM",
        "doc_url": "https://github.com/Organizr/docker-organizr",
        "caveat": None,
    },
]

CATALOG_BY_ID = {entry["id"]: entry for entry in CATALOG}

assert len(CATALOG) == 20, f"catalog registry drifted from 20 entries: {len(CATALOG)}"
