# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-plays-by-date -f
complete -c stack-tautulli-plays-by-date -d 'Show Tautulli plays-by-date trend'
