# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-popular -f
complete -c stack-letterboxd-radarr-popular -l no-search
complete -c stack-letterboxd-radarr-popular -l no-monitor
complete -c stack-letterboxd-radarr-popular -l limit -r
complete -c stack-letterboxd-radarr-popular -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-letterboxd-radarr-popular -d 'Add Letterboxd\'s popular films to Radarr'
