# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tmdb-missing -f
complete -c stack-tmdb-missing -d 'Find Plex items missing a TMDb link, write ~/missing.txt'
