# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-list -f
complete -c stack-letterboxd-radarr-list -l no-search
complete -c stack-letterboxd-radarr-list -l no-monitor
complete -c stack-letterboxd-radarr-list -l limit -r
complete -c stack-letterboxd-radarr-list -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-letterboxd-radarr-list -l tags-as-radarr-tags
complete -c stack-letterboxd-radarr-list -l sonarr-crossover
complete -c stack-letterboxd-radarr-list -l rating-quality-map -r
complete -c stack-letterboxd-radarr-list -d 'Add every film in a Letterboxd list to Radarr'
