# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-import-candidates -f
complete -c stack-arr-import-candidates -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr-import-candidates -d 'List files ready to manually import in an *arr app'
