# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-import-all -f
complete -c stack-arr-import-all -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr-import-all -d 'Import every stuck queue file for an *arr app in one go'
