# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-users -f
complete -c stack-tautulli-users -d 'List Plex users known to Tautulli'
