# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-kometa-logs -f
complete -c stack-kometa-logs -d 'Tail Kometa container logs'
