# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-sessions -f
complete -c stack-plex-sessions -d 'Show active Plex streaming sessions'
