# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr -f
complete -c stack-arr -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr -n 'test (count (commandline -opc)) -eq 2' -a 'rss-sync search-missing unstick unstick-importing'
complete -c stack-arr -d 'Trigger an *arr app maintenance action'
