# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-garbage-collect-blobs -f
complete -c stack-plex-garbage-collect-blobs -d 'Garbage-collect unused metadata blobs'
