# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-bazarr-search-missing -f
complete -c stack-bazarr-search-missing -d 'Trigger an on-demand Bazarr missing-subtitle search'
