# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-organizr-tabs -f
complete -c stack-organizr-tabs -d 'List Organizr\'s configured dashboard tabs'
