# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex -f
complete -c stack-plex -n 'test (count (commandline -opc)) -eq 1' -a 'scan empty-trash optimize-db clean-bundles'
complete -c stack-plex -d 'Trigger a Plex maintenance action'
