# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-prefetcharr-config -f
complete -c stack-prefetcharr-config -d 'Show effective Prefetcharr config'
