# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-collection -f
complete -c stack-letterboxd-radarr-collection -l no-search
complete -c stack-letterboxd-radarr-collection -l no-monitor
complete -c stack-letterboxd-radarr-collection -l limit -r
complete -c stack-letterboxd-radarr-collection -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-letterboxd-radarr-collection -d 'Add every film in a Letterboxd collection to Radarr'
