# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-garbage-collect-media -f
complete -c stack-plex-garbage-collect-media -d 'Garbage-collect unused library media records'
