# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-sonarr-import-custom-list -f
complete -c stack-sonarr-import-custom-list -l no-search
complete -c stack-sonarr-import-custom-list -d 'Add a generic JSON/RSS feed as a Sonarr import list'
