# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-wrapperr-links -f
complete -c stack-wrapperr-links -d 'List Wrapperr public share links'
