# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-intro-markers -f
complete -c stack-plex-generate-intro-markers -d 'Generate intro markers for eligible media'
