# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-libraries -f
complete -c stack-tautulli-libraries -d 'Show Tautulli per-library item counts'
