# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-rule-detail -f
complete -c stack-maintainerr-rule-detail -n 'test (count (commandline -opc)) -eq 1' -d 'rule_id'
complete -c stack-maintainerr-rule-detail -d 'Show one Maintainerr rule in full'
