# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-refresh-local-media -f
complete -c stack-plex-refresh-local-media -d 'Refresh local media file changes'
