# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-import-lists -f
complete -c stack-import-lists -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-import-lists -d 'List configured import lists for Radarr/Sonarr'
