# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-safety-check -f
complete -c stack-maintainerr-safety-check -d 'Alert if any Maintainerr rule is active'
