# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-missing-aired -f
complete -c stack-arr-missing-aired -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr radarr_anime sonarr_anime'
complete -c stack-arr-missing-aired -d 'List monitored items missing a file that have already aired/released'
