# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-logs -f
complete -c stack-arr-logs -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr prowlarr'
complete -c stack-arr-logs -d 'Tail an *arr app\'s container log directly'
