# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-loop-candidates -f
complete -c stack-loop-candidates -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-loop-candidates -d 'Looping titles in the queue-autofix history, with remediation'
