# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-duplicates -f
complete -c stack-plex-duplicates -n 'test (count (commandline -opc)) -eq 1' -d 'min_gb'
complete -c stack-plex-duplicates -d 'Flag Plex movies carrying redundant duplicate files'
