# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-refresh-libraries -f
complete -c stack-plex-refresh-libraries -d 'Refresh metadata for every library'
