# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-rating-mdblist -f
complete -c stack-rating-mdblist -d 'Look up a title\'s MDBList score'
