# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-gaps2-status -f
complete -c stack-gaps2-status -d 'GAPS-2 scan state and last scan per library'
