# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-backup-database -f
complete -c stack-plex-backup-database -d 'Back up Plex\'s database to its configured backup directory'
