# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-tracked -f
complete -c stack-letterboxd-radarr-tracked -d 'List every Letterboxd list registered for nightly sync'
