# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-kometa-status -f
complete -c stack-kometa-status -d 'Show time until next scheduled Kometa run'
