# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-loop-exclude -f
complete -c stack-loop-exclude -l yes -d 'Skip the confirmation prompt'
complete -c stack-loop-exclude -l y -d 'Skip the confirmation prompt'
complete -c stack-loop-exclude -d 'Add a Radarr movie to Exclusions'
