# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-lingarr-shows -f
complete -c stack-lingarr-shows -d 'List shows Lingarr tracks'
