# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-speedtest-latest -f
complete -c stack-speedtest-latest -d 'Show latest speedtest result'
