# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-clean-log-files -f
complete -c stack-plex-clean-log-files -d 'Delete old supplemental Plex log files'
