# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-collection-media -f
complete -c stack-maintainerr-collection-media -n 'test (count (commandline -opc)) -eq 1' -d 'collection_id'
complete -c stack-maintainerr-collection-media -d 'Show media in one Maintainerr collection'
