# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-backlog-status -f
complete -c stack-backlog-status -d 'Show every app\'s wanted/missing backlog with a throughput-projected ETA'
