# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-ntfy-publish -f
complete -c stack-ntfy-publish -n 'test (count (commandline -opc)) -eq 1' -d 'topic'
complete -c stack-ntfy-publish -n 'test (count (commandline -opc)) -eq 2' -d 'message'
complete -c stack-ntfy-publish -d 'Publish a message to an ntfy topic'
