# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-toggle-search -f
complete -c stack-arr-toggle-search -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr all'
complete -c stack-arr-toggle-search -n 'test (count (commandline -opc)) -eq 2' -a 'on off'
complete -c stack-arr-toggle-search -d 'Turn RSS sync + automatic search on/off for Radarr/Sonarr indexers'
