# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-prefetcharr-logs -f
complete -c stack-prefetcharr-logs -d 'Tail Prefetcharr log file'
