# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-sonarr-fix-episode-monitoring -f
complete -c stack-sonarr-fix-episode-monitoring -d 'Fix unmonitored episodes under monitored Sonarr series'
