# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-ad-markers -f
complete -c stack-plex-generate-ad-markers -d 'Generate ad-break markers for eligible media'
