# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tmdb-import-keyword -f
complete -c stack-tmdb-import-keyword -l no-search
complete -c stack-tmdb-import-keyword -d 'Add a TMDB keyword-filtered list as a Radarr import list'
