# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mdblist-import -f
complete -c stack-mdblist-import -l no-search
complete -c stack-mdblist-import -l no-monitor
complete -c stack-mdblist-import -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-mdblist-import -l limit -r
complete -c stack-mdblist-import -d 'Import an MDBList list into Radarr and Sonarr'
