# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-track -f
complete -c stack-letterboxd-radarr-track -l label -r
complete -c stack-letterboxd-radarr-track -d 'Register a Letterboxd list for nightly diff-only sync'
