# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-lingarr-stats -f
complete -c stack-lingarr-stats -d 'Show Lingarr lifetime translation stats'
