# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-rating-imdb -f
complete -c stack-rating-imdb -d 'Look up a title\'s IMDb rating'
