# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-clear-blocklist -f
complete -c stack-arr-clear-blocklist -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr-clear-blocklist -d 'Clear every blocklisted release in Radarr/Sonarr'
