# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-server-info -f
complete -c stack-tautulli-server-info -d 'Show the Plex server Tautulli is tracking'
