# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-collections -f
complete -c stack-maintainerr-collections -d 'List Plex collections Maintainerr tracks'
