# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-butler-all -f
complete -c stack-plex-butler-all -d 'Trigger every Plex Butler maintenance task, one at a time'
