# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-newapps-status -f
complete -c stack-newapps-status -d 'Health sweep of the new apps'
