# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-logs -f
complete -c stack-maintainerr-logs -d 'Tail Maintainerr container logs'
