# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-trakt-import-list -f
complete -c stack-trakt-import-list -l no-search
complete -c stack-trakt-import-list -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-trakt-import-list -d 'Add a public Trakt list as a Radarr/Sonarr import list'
