# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-bazarr-history -f
complete -c stack-bazarr-history -d 'Show recent Bazarr subtitle download history'
