# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-voice-activity -f
complete -c stack-plex-generate-voice-activity -d 'Generate voice-activity data (used for dialogue boost)'
