# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-recently-added -f
complete -c stack-plex-recently-added -d 'Show recently added items visible in Plex'
