# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-prefetcharr-plex-link-check -f
complete -c stack-prefetcharr-plex-link-check -d 'Check Prefetcharr-Plex config drift'
