# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-updates -f
complete -c stack-plex-updates -d 'Check for a Plex update (check only, does not apply it)'
