# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-seerr-requests -f
complete -c stack-seerr-requests -n 'test (count (commandline -opc)) -eq 1' -a 'pending approved available all'
complete -c stack-seerr-requests -d 'List Seerr media requests by status'
