# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-butler -f
complete -c stack-plex-butler -n 'test (count (commandline -opc)) -eq 1' -a "(__stack_plex_butler_tasks)"
complete -c stack-plex-butler -d 'Trigger a named Plex Butler task on demand'
