# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-scrutiny-summary -f
complete -c stack-scrutiny-summary -d 'All-disk SMART status at a glance'
