# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mdblist-radarr-untrack -f
complete -c stack-mdblist-radarr-untrack -d 'Stop nightly-syncing a tracked MDBList list'
