# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-loudness-analysis -f
complete -c stack-plex-loudness-analysis -d 'Analyze audio loudness for volume leveling'
