# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-customformat-diff -f
complete -c stack-customformat-diff -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-customformat-diff -d 'Diff current Radarr/Sonarr custom-format scores against the last check'
