# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-watched -f
complete -c stack-letterboxd-radarr-watched -l no-search
complete -c stack-letterboxd-radarr-watched -l no-monitor
complete -c stack-letterboxd-radarr-watched -l limit -r
complete -c stack-letterboxd-radarr-watched -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-letterboxd-radarr-watched -d 'Add every film a Letterboxd user has watched to Radarr'
