# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plexanisync-last-run -f
complete -c stack-plexanisync-last-run -d 'Last PlexAniSync run: time, exit code, matched count'
