# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mdblist-radarr-track -f
complete -c stack-mdblist-radarr-track -l label -r
complete -c stack-mdblist-radarr-track -d 'Register an MDBList list for nightly diff-only sync'
