# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-bazarr-wanted -f
complete -c stack-bazarr-wanted -d 'List movies/episodes still missing subtitles in Bazarr'
