# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-kometa-run-now -f
complete -c stack-kometa-run-now -d 'Trigger an immediate Kometa run'
