# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-clean-cache-files -f
complete -c stack-plex-clean-cache-files -d 'Delete old Plex cache files'
