# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-queue-errors -f
complete -c stack-arr-queue-errors -d 'Show only errored/warning queue items across all arr apps'
