# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-wrapperr-reports -f
complete -c stack-wrapperr-reports -d 'List Wrapperr saved reports'
