# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-scrutiny-disk -f
complete -c stack-scrutiny-disk -n 'test (count (commandline -opc)) -eq 1' -a 'uuid device-name serial'
complete -c stack-scrutiny-disk -d 'Per-disk SMART detail (omit arg for the only disk)'
