# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-history -f
complete -c stack-letterboxd-radarr-history -d 'Show recent Letterboxd sync run history'
