# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-prefetcharr-status -f
complete -c stack-prefetcharr-status -d 'Show Prefetcharr container/last-event status'
