# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-cutoff-unmet -f
complete -c stack-cutoff-unmet -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-cutoff-unmet -d 'List items below quality cutoff in Radarr/Sonarr'
