# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-terminate-stream -f
complete -c stack-tautulli-terminate-stream -n 'test (count (commandline -opc)) -eq 1' -d 'session_key'
complete -c stack-tautulli-terminate-stream -d 'Terminate a Plex stream via Tautulli'
