# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-wrapperr-tautulli-link-check -f
complete -c stack-wrapperr-tautulli-link-check -d 'Check Wrapperr-Tautulli key drift'
