# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-maintainerr-rules -f
complete -c stack-maintainerr-rules -d 'List configured Maintainerr rules'
