# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-gaps2-scan -f
complete -c stack-gaps2-scan -n 'test (count (commandline -opc)) -eq 1' -d 'plex-library'
complete -c stack-gaps2-scan -d 'Sweep libraries for collection/franchise gaps'
