# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tmdb-import-company -f
complete -c stack-tmdb-import-company -l no-search
complete -c stack-tmdb-import-company -d 'Add a TMDB studio filmography as a Radarr import list'
