# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-ntfy-topics -f
complete -c stack-ntfy-topics -d 'List topics this stack publishes to on ntfy'
