# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-backlog -f
complete -c stack-arr-backlog -d 'Show an arr app\'s internal command queue backlog (searches, RSS sync, bulk moves, etc)'
