# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-list-implementations -f
complete -c stack-arr-list-implementations -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr radarr_anime sonarr_anime'
complete -c stack-arr-list-implementations -d 'List every import-list implementation Radarr/Sonarr supports'
