# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-process-assets -f
complete -c stack-plex-process-assets -d 'Process pending local assets (posters, themes, etc)'
