# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-bazarr-provider-status -f
complete -c stack-bazarr-provider-status -d 'Show per-provider throttle/error state in Bazarr'
