# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-loop-unmonitor -f
complete -c stack-loop-unmonitor -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-loop-unmonitor -d 'Unmonitor a looping movie or episode by id'
