# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-prowlarr-indexers -f
complete -c stack-prowlarr-indexers -d 'List Prowlarr indexers with enabled state and priority'
