# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-radarr-import-list -f
complete -c stack-radarr-import-list -l no-search
complete -c stack-radarr-import-list -d 'Add a hosted Radarr-list-format URL as a Radarr import list'
