# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-sync-check -f
complete -c stack-tautulli-sync-check -d 'Check Tautulli-Plex config drift'
