# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-chapter-thumbs -f
complete -c stack-plex-generate-chapter-thumbs -d 'Generate chapter thumbnail (BIF) files'
