# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-scrutiny-collect -f
complete -c stack-scrutiny-collect -d 'Run the SMART collector now'
