# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-libraries -f
complete -c stack-plex-libraries -d 'List Plex library names (e.g. for stack-plex-empty-trash)'
