# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-lingarr-recent-translations -f
complete -c stack-lingarr-recent-translations -d 'Show recent Lingarr translation events'
