# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-list-random -f
complete -c stack-letterboxd-radarr-list-random -d 'Add a random featured Letterboxd list to Radarr'
