# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-deep-media-analysis -f
complete -c stack-plex-deep-media-analysis -d 'Run full deep media analysis across every library (loudness, chapter thumbs, markers, voice activity)'
