# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-recently-added -f
complete -c stack-tautulli-recently-added -d 'Show recently-added items via Tautulli'
