# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-queue-autofix -f
complete -c stack-queue-autofix -d 'Blocklist+research stuck Radarr/Sonarr queue items, check NzbDAV health'
