# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-upgrade-media-analysis -f
complete -c stack-plex-upgrade-media-analysis -d 'Re-run analysis for items whose analysis version is outdated'
