# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-import-starvation -f
complete -c stack-arr-import-starvation -d 'Detect Radarr/Sonarr imports starved by a search backlog'
