# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-gaps2-missing -f
complete -c stack-gaps2-missing -n 'test (count (commandline -opc)) -eq 1' -d 'plex-library'
complete -c stack-gaps2-missing -d 'Titles missing from collections/franchises, with their target Arr'
