# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-import-watchlist -f
complete -c stack-plex-import-watchlist -l no-search
complete -c stack-plex-import-watchlist -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-plex-import-watchlist -d 'Add your Plex watchlist as a Radarr/Sonarr import list'
