# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-lingarr-movies -f
complete -c stack-lingarr-movies -d 'List movies Lingarr tracks'
