# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-automatic-updates -f
complete -c stack-plex-automatic-updates -d 'Trigger Plex\'s own app-update check (unrelated to library media)'
