# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-credits-markers -f
complete -c stack-plex-generate-credits-markers -d 'Generate end-credits markers for eligible media'
