# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-command-queue-summary -f
complete -c stack-command-queue-summary -d 'Show command queue backlog across all arr apps at once'
