# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-lingarr-logs -f
complete -c stack-lingarr-logs -d 'Tail Lingarr container logs'
