# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-import -f
complete -c stack-arr-import -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr-import -n 'test (count (commandline -opc)) -eq 2' -d 'index'
complete -c stack-arr-import -d 'Import a file listed by stack-arr-import-candidates'
