# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-refresh-epg -f
complete -c stack-plex-refresh-epg -d 'Refresh Live TV/DVR EPG guide data'
