# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plexanisync-logs -f
complete -c stack-plexanisync-logs -d 'Tail PlexAniSync container logs'
