# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mdblist-radarr-tracked -f
complete -c stack-mdblist-radarr-tracked -d 'List every MDBList list registered for nightly sync'
