# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-generate-media-index -f
complete -c stack-plex-generate-media-index -d 'Generate media index files used for fast seeking'
