# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-analyze -f
complete -c stack-plex-analyze -n 'test (count (commandline -opc)) -eq 1' -d 'library name'
complete -c stack-plex-analyze -d 'Queue deep media analysis on one Plex library, or all of them'
