# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plexanisync-run-now -f
complete -c stack-plexanisync-run-now -d 'Start an out-of-schedule PlexAniSync sync to AniList'
