# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-recently-added -f
complete -c stack-arr-recently-added -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-arr-recently-added -d 'List recently added items in Radarr/Sonarr with file status'
