# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-stats -f
complete -c stack-tautulli-stats -d 'Show Tautulli home stats'
