# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-notifiers -f
complete -c stack-tautulli-notifiers -d 'List configured Tautulli notifiers'
