# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-letterboxd-radarr-watchlist -f
complete -c stack-letterboxd-radarr-watchlist -l no-search
complete -c stack-letterboxd-radarr-watchlist -l no-monitor
complete -c stack-letterboxd-radarr-watchlist -l limit -r
complete -c stack-letterboxd-radarr-watchlist -l dry-run -d 'Report what would happen, change nothing'
complete -c stack-letterboxd-radarr-watchlist -d 'Add every film in a Letterboxd watchlist to Radarr'
