# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-scrutiny-alert-test -f
complete -c stack-scrutiny-alert-test -d 'Fire Scrutiny\'s test notification through ntfy'
