# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mdblist-radarr-history -f
complete -c stack-mdblist-radarr-history -d 'Show recent MDBList sync run history'
