# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-speedtest-run-now -f
complete -c stack-speedtest-run-now -d 'Trigger an out-of-schedule speedtest'
