# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tautulli-user-history -f
complete -c stack-tautulli-user-history -n 'test (count (commandline -opc)) -eq 1' -d 'user_id'
complete -c stack-tautulli-user-history -d 'Show watch history for one Tautulli user'
