# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-gaps2-push -f
complete -c stack-gaps2-push -n 'test (count (commandline -opc)) -eq 2' -d 'plex-library'
complete -c stack-gaps2-push -d 'Add one missing title to the Arr instance its library maps to'
