# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-plex-import-rss -f
complete -c stack-plex-import-rss -l no-search
complete -c stack-plex-import-rss -n 'test (count (commandline -opc)) -eq 1' -a 'radarr sonarr'
complete -c stack-plex-import-rss -d 'Add a Plex Watchlist RSS feed as a Radarr/Sonarr import list'
