function stack-help --description 'List all stack-* terminal commands for the media stack'
    echo 'Media-stack terminal commands (all hit Control Panel on 192.168.4.105:8420):'
    echo '  stack-status                                    live health of every container'
    echo '  stack-arr <radarr|sonarr> <rss-sync|search-missing|unstick|unstick-importing>'
    echo '                                                   unstick-importing: clear a wedged "importing" download (dead-article test)'
    echo '  stack-arr-import-candidates <radarr|sonarr>'
    echo '                                                   list files ready to manually import'
    echo '  stack-arr-import <radarr|sonarr> <index>'
    echo '                                                   import one, by index from the above'
    echo '  stack-arr-import-all <radarr|sonarr>'
    echo '                                                   import every stuck queue file in one go'
    echo '  stack-arr-backlog <radarr|sonarr>'
    echo '                                                   show the app'"'"'s internal command-queue backlog'
    echo '  stack-arr-missing-aired <radarr|sonarr>          monitored + missing + already aired/released'
    echo '  stack-plex <scan|empty-trash|optimize-db|clean-bundles>'
    echo '  stack-plex-libraries                            list Plex library names'
    echo '  stack-plex-updates                              check for a Plex update (check only)'
    echo '  stack-nzbdav-queue                              show NzbDAV'"'"'s current download queue'
    echo '  stack-nzbdav-history [limit]                    show NzbDAV'"'"'s recent download history'
    echo '  stack-nzbdav-delete-failures                    delete all Failed entries from NzbDAV history'
    echo ''
    echo '  stack-queue-status                              every app'"'"'s queue with live-measured speed/ETA'
    echo '  stack-backlog-status                            every app'"'"'s wanted/missing backlog with throughput ETA'
    echo '  stack-container <restart|stop|start> <name>     control a single container'
    echo '  stack-restart-all [-y]                          restart the whole stack (confirms first)'
    echo ''
    echo 'Diagnostics/audit (added after a live resource+wiring audit found real gaps):'
    echo '  stack-resource-check                            containers missing mem_limit/cpus'
    echo '  stack-log-levels [reset]                        check, or reset, every Servarr app'"'"'s log level'
    echo '  stack-mount-health                              check every known FUSE mountpoint'
    echo '  stack-oom-check                                 containers Docker has recorded an OOM-kill for'
    echo '  stack-perms-check                               config files unreadable by group/other (won'"'"'t be backed up)'
    echo '  stack-cleanuparr-instances                      which *arr apps Cleanuparr actually has connected'
    echo '  stack-arr-logs <app> [lines]                    tail an *arr app'"'"'s container log directly'
    echo '  stack-plex-empty-trash [library ...]            empty trash on one library, or all of them'
    echo '  stack-image-check                               check pinned images for a newer registry digest'
    echo '  stack-disk-config-sizes                                per-app config/ directory size, largest first'
    echo '  stack-version                                   README'"'"'s declared version + live container count'
    echo ''
    echo 'Added in one pass after a real "why haven'"'"'t my shows been processed" session:'
    echo '  stack-command-queue-summary                     backlog across every *arr app at once'
    echo '  stack-arr-recently-added <radarr|sonarr> [limit]    recently added, with file/episode status'
    echo '  stack-plex-duplicates [min_gb]                  movies carrying redundant duplicate files'
    echo '  stack-prowlarr-indexers                         every indexer'"'"'s enabled state + priority'
    echo '  stack-plex-sessions                             who'"'"'s watching what right now'
    echo '  stack-seerr-requests [pending|approved|available|all]'
    echo '                                                   media requests sitting in Seerr'
    echo '  stack-cleanuparr-strikes [limit]                recent stalled/slow/malware strikes'
    echo '  stack-arr-queue-errors                          only queue items already flagged as a problem'
    echo '  stack-notify-test                               send a test message to the Discord webhook'
    echo '  stack-top [cpu|mem] [limit]                     top containers by resource usage'
    echo '  stack-cutoff-unmet <radarr|sonarr> [limit]      items below their quality cutoff'
    echo '  stack-import-lists <radarr|sonarr>              configured import lists + enabled state'
    echo '  stack-nzbdav-stats                              aggregate queue/history counts'
    echo '  stack-plex-recently-added [limit]                what'"'"'s actually visible in Plex now'
    echo ''
    echo 'Ratings + list import (standalone OMDB_KEY/MDBLIST_KEY .env secrets, no Kometa dependency):'
    echo '  stack-rating-imdb <imdb-id>                     a title'"'"'s IMDb rating, via OMDb'
    echo '  stack-rating-mdblist <imdb-id>                  a title'"'"'s MDBList score + IMDb sub-rating'
    echo '  stack-mdblist-import <mdblist-list-url> [--no-search] [--no-monitor] [--dry-run] [--limit N]'
    echo '                                                   import a public MDBList list to Radarr + Sonarr'
    echo ''
    echo 'Letterboxd to Radarr (all take [--no-search] [--no-monitor] [--dry-run]; lists also [--limit N]):'
    echo '  stack-letterboxd-radarr <film-url>              add one Letterboxd film to Radarr'
    echo '  stack-letterboxd-radarr-list <list-url>         add every film in a Letterboxd list'
    echo '  stack-letterboxd-radarr-watchlist <user-url>    add every film in a user'"'"'s watchlist'
    echo '  stack-letterboxd-radarr-watched <user-url>      add every film a user has watched'
    echo '  stack-letterboxd-radarr-collection <coll-url>   add every film in a Letterboxd collection'
    echo '  stack-letterboxd-radarr-filmography <role> <slug>'
    echo '                                                   add a person'"'"'s whole filmography by role'
    echo '  stack-letterboxd-radarr-popular                 add Letterboxd'"'"'s current popular films'
    echo ''
    echo '2026-07-30 awesome-arr additions (tautulli/wrapperr/maintainerr/prefetcharr/lingarr/kometa):'
    echo '  stack-tautulli-activity                         current Plex streams via Tautulli'
    echo '  stack-tautulli-terminate-stream <session_key>   kill one active stream'
    echo '  stack-tautulli-history [limit]                  recent watch history'
    echo '  stack-tautulli-stats                            home stat cards (top movies/shows/users)'
    echo '  stack-tautulli-users                             every known Plex user + lifetime stats'
    echo '  stack-tautulli-user-history <user_id> [limit]   watch history for one user'
    echo '  stack-tautulli-libraries                        per-library item counts'
    echo '  stack-tautulli-recently-added [limit]            Tautulli'"'"'s own recently-added feed'
    echo '  stack-tautulli-server-info                      which Plex server Tautulli is tracking'
    echo '  stack-tautulli-newsletters                      configured newsletters, if any'
    echo '  stack-tautulli-notifiers                        notification agents configured in Tautulli'
    echo '  stack-tautulli-plays-by-date [days]             daily play-count trend'
    echo '  stack-tautulli-sync-check                       confirm Tautulli tracks this stack'"'"'s real Plex'
    echo '  stack-wrapperr-status                           reachability + Tautulli connection saved?'
    echo '  stack-wrapperr-reports                          saved report definitions'
    echo '  stack-wrapperr-links                            generated public share links'
    echo '  stack-wrapperr-tautulli-link-check               confirm Wrapperr'"'"'s saved Tautulli key matches live'
    echo '  stack-maintainerr-rules                         configured rules (expected empty)'
    echo '  stack-maintainerr-rule-detail <rule_id>         full definition of one rule'
    echo '  stack-maintainerr-collections                   Plex collections being tracked'
    echo '  stack-maintainerr-collection-media <collection_id>'
    echo '                                                   media items in one tracked collection'
    echo '  stack-maintainerr-logs [lines]                  tail Maintainerr'"'"'s container logs'
    echo '  stack-maintainerr-safety-check                  ALERT if any rule is ever active (zero expected)'
    echo '  stack-maintainerr-plex-link-check                confirm Maintainerr'"'"'s Plex host matches real Plex'
    echo '  stack-prefetcharr-logs [lines]                  tail Prefetcharr'"'"'s log file'
    echo '  stack-prefetcharr-status                        container state + last prefetch event'
    echo '  stack-prefetcharr-config                        effective PREFETCHARR_CONFIG as deployed'
    echo '  stack-prefetcharr-plex-link-check                 confirm Prefetcharr'"'"'s baked-in Plex URL is current'
    echo '  stack-lingarr-stats                             lifetime translation totals'
    echo '  stack-lingarr-movies [limit]                    movies Lingarr tracks via Radarr'
    echo '  stack-lingarr-shows [limit]                     shows Lingarr tracks via Sonarr'
    echo '  stack-lingarr-logs [lines]                      tail Lingarr'"'"'s container logs'
    echo '  stack-lingarr-recent-translations                recent individual translation events'
    echo '  stack-kometa-status                             time until next scheduled Kometa run'
    echo '  stack-kometa-run-now                            trigger an immediate run (detached)'
    echo '  stack-kometa-logs [lines]                       tail Kometa'"'"'s container logs'
    echo '  stack-kometa-last-run-result                    outcome of the last completed run'
    echo '  stack-kometa-config                             which libraries config.yml is set to touch'
    echo '  stack-newapps-status                            health sweep of all new apps at once'
    echo ''
    echo 'new-services batch (PLANS.md Phases 1-3, 2026-08):'
    echo '  stack-ntfy-publish <topic> <message>            push a message to an ntfy topic'
    echo '  stack-ntfy-topics                               list configured ntfy topics'
    echo '  stack-speedtest-latest                          most recent speedtest (down/up/ping/jitter)'
    echo '  stack-speedtest-history [days]                  speedtest results over the last N days (default 7)'
    echo '  stack-speedtest-run-now                         trigger an out-of-schedule speedtest'
    echo '  stack-organizr-tabs                             Organizr'"'"'s dashboard tabs + which services lack one'
    echo '  stack-organizr-sync                             add a tab for any service missing one (additive only)'
    echo '  stack-scrutiny-summary                          all-disk SMART status at a glance'
    echo '  stack-scrutiny-disk [uuid|name|serial]          per-disk SMART detail (omit arg for the only disk)'
    echo '  stack-scrutiny-collect                          run the SMART collector now, not at midnight'
    echo '  stack-scrutiny-alert-test                       fire Scrutiny'"'"'s test alert through ntfy'
    echo '  stack-gaps2-status                              GAPS-2 sweep state + last scan per library'
    echo '  stack-gaps2-scan [library] [--full]             sweep for collection/franchise gaps (all libraries if none named)'
    echo '  stack-gaps2-missing [library] [limit]           missing titles, each tagged with its target Arr'
    echo '  stack-gaps2-push <id> <library>                 add one missing title to the Arr its library maps to'
    echo '  stack-watchstate-status                         WatchState tracked items + import schedule'
    echo '  stack-watchstate-import-now                     queue an out-of-schedule import from Plex'
    echo '  stack-watchstate-history [title] [limit]        watch history, optionally filtered to a title'
end
